sudo: required

language: java

python:
  - "3.6"

os:
  - linux

services:
  - mysql

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

before_install:
  - pip install PyMySQL --user

before_script:
  - mysqladmin -u root password "123456"
  - python init_db.py

script:
  - mvn test
